# Generated by Django 3.0.6 on 2020-05-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20200523_2244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visitors',
            new_name='Visitor',
        ),
    ]
