# Generated by Django 3.0.6 on 2020-05-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20200523_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='phone_no',
            field=models.CharField(max_length=12),
        ),
    ]
